name: Build and Push OCI Image

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 4 * * 1'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: quay.io/buildah/stable
      options: --privileged --device /dev/fuse

    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Login to registry
        run: |
          buildah login \
            -u james.oates \
            -p ${{ secrets.FORGEJO_TOKEN }} \
            forge.isohex.uk

      - name: Build
        run: |
          buildah build \
            --build-arg FEDORA_MAJOR_VERSION=44 \
            --squash-all \
            -t forge.isohex.uk/glarion/glarion:latest \
            -t "forge.isohex.uk/glarion/glarion:sha-${GITHUB_SHA:0:7}" \
            -f Containerfile \
            .

      - name: Push
        run: |
          buildah push forge.isohex.uk/glarion/glarion:latest
          buildah push "forge.isohex.uk/glarion/glarion:sha-${GITHUB_SHA:0:7}"
