name: Build and Push OCI Image

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 4 * * 1'
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: glarion
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  FEDORA_MAJOR_VERSION: "44"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free up runner disk space
        run: |
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc /usr/local/.ghcup /opt/hostedtoolcache/CodeQL
          sudo docker image prune -af
          df -h /

      - name: Login to GHCR
        run: |
          sudo podman login \
            -u ${{ github.actor }} \
            -p ${{ secrets.GITHUB_TOKEN }} \
            ghcr.io

      - name: Build
        run: |
          sudo podman build \
            --build-arg FEDORA_MAJOR_VERSION=${FEDORA_MAJOR_VERSION} \
            --layers \
            --cache-from "${IMAGE_REGISTRY}/${IMAGE_NAME}-cache" \
            --cache-to "${IMAGE_REGISTRY}/${IMAGE_NAME}-cache" \
            -t "${IMAGE_REGISTRY}/${IMAGE_NAME}:latest" \
            -t "${IMAGE_REGISTRY}/${IMAGE_NAME}:${FEDORA_MAJOR_VERSION}" \
            -t "${IMAGE_REGISTRY}/${IMAGE_NAME}:sha-${GITHUB_SHA:0:7}" \
            -f Containerfile \
            .

      - name: Push
        run: |
          sudo podman push --digestfile /tmp/image-digest "${IMAGE_REGISTRY}/${IMAGE_NAME}:latest"
          sudo podman push "${IMAGE_REGISTRY}/${IMAGE_NAME}:${FEDORA_MAJOR_VERSION}"
          sudo podman push "${IMAGE_REGISTRY}/${IMAGE_NAME}:sha-${GITHUB_SHA:0:7}"

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign image
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
          COSIGN_PASSWORD: ""
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          cosign sign -y --key env://COSIGN_PRIVATE_KEY "${IMAGE_REGISTRY}/${IMAGE_NAME}@$(cat /tmp/image-digest)"
